name: 'Execução Manual'

on: 
  workflow_dispatch:

jobs:
  work-tests:
    
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:

      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4

      - name: Instalando o Yarn
        run: npm install -g yarn

      - name: Instalando as dependências
        run:  yarn

    
      
      - name: Executando Testes do Trabalho
      
        run: npx mocha CI/pgats-ci-lab/trabalhos/trabalho-final.js

      